name: Hello world
on:   #all the triggers follow the key "on:"
  push: #webhook trigger => are based on an event in GitHub, push, pull, merge, pull_request
    branches:
      - 'main'
      - 'release/**'
    paths:
      - 'docs/**'
  schedule: #schedule trigger => are based on cron expressions
    # Runs at every 15th minute
    - cron:  '*/15 * * * *'

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

    job_2:
      runs-on: ubuntu-latest
      needs: job_1
      steps:
        - run: "echo Job: ${{ github.job }}"

    job_3:
      runs-on: ubuntu-latest
      needs: job_1
      steps:
        - run: "echo Job: ${{ github.job }}"

  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World!"

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
