name: Hello world
on:   #all the triggers follow the key "on:"
  push: #webhook trigger => are based on an event in GitHub, push, pull, merge, pull_request
    branches:
      - 'main'
      - 'release/**'
    paths:
      - 'docs/**'
  schedule: #schedule trigger => are based on cron expressions
    # Runs at every 15th minute
    - cron:  '*/15 * * * *'
  workflow_dispatch: #manually
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World!"

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
